#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Computer science, machine learning, and related stuff

# Short bio or description (displayed in the header)
description: Musings on research, teaching and the like

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# choose a theme
theme: jekyll-theme-minimal
